### ISSUE TITLE
I can't install the package for Macintosh.

### ISSUE THREAD

**Issue by varoarana** [DavidStirling/QuantiFish#7]
When I download the program and try to open it, the computer shows a message saying "The application QuantiFish cannot be opened." I currently have macOS Ventura version 13.3.1, and I'm not sure if that's the issue. Thank you!

**Comment by DavidStirling** [comment]
The last mac builds were for macOS 10.x, so the chances are something on newer releases broke them. I'll see if I can get some builds working on modern systems.

**Comment by varoarana** [comment]
Great! Thank you very much, that would be very helpful for me and our laboratory! Thanks for your work. I hope you can solve it, but please don't feel pressured. :)

**Comment by varoarana** [comment]
Great! Thank you very much, that would be very helpful for me and our lab! Thanks for your work. I hope you can solve it, but please don't feel pressured.

**Comment by DavidStirling** [comment]
Hey @varoarana, could you try the builds available [here](https://github.com/DavidStirling/QuantiFish/releases/tag/v2.1.2)?

Getting builds running on modern macos was... tricky. If there are still problems it should be much easier to troubleshoot going forwards though. We're now targetting macos 13+.

**Comment by varoarana** [comment]
Hey @DavidStirling,

Thank you so much for all your hard work and effort. The program now opens without any issues. I understand how difficult it is to resolve these problems, and I really appreciate that you fixed it so quickly. I'll be running some tests throughout the day to provide you with better feedback.
